[cum_ret,market,market_vr, cumprod_ret_a, daily_ret, daily_portfolio] = ubah_run_self( data);
A = cumprod_ret_a;
[cum_ret, cumprod_ret, daily_ret, daily_portfolio] = best_run_self( data,market,market_vr);
y = cumprod_ret;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[cum_ret, cumprod_ret, daily_ret, daily_portfolio] = corn_run_self(data,market,market_vr);
y = cumprod_ret;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[cum_ret, cumprod_ret, daily_ret, daily_portfolio]   = olmar2_run_self( data ,market,market_vr);
y = cumprod_ret;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[cum_wealth, daily_incre_fact, daily_port_total] = RPRT_run(data,market,market_vr,tran_cost);
y = cum_wealth;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[total_ret, day_ret] = weighted_run(data,tc,market,market_vr);
y = total_ret;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[ cum_wealth, daily_incre_fact, daily_port_total] = PPT_run(data, win_size, tran_cost,market,market_vr);
y = cum_wealth;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[ cum_wealth, daily_incre_fact, daily_port_total] = AICTR_run( data,win_size,tran_cost,market,market_vr);
y = cum_wealth;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
[ cum_wealth, daily_incre_fact, daily_port_total] = SPO_kp_run( data,opts,market,market_vr);
y = cum_wealth;
[ xhat,tV,ttesttotalpval] = regressolsttestalphapval( A,y );
fprintf('p value is \t%.5f\n',ttesttotalpval(1));
